application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

spring:
  data:
    mongodb:
      database: students
      host: localhost
      port: 27017
app:
  user: admin
  password: password
logging:
  level:
    org.springframework: DEBUG